apiVersion: v1
kind: Pod
metadata:
  name: test-ebs
spec:
  containers:
  - image: centos 
    name: centos
    command: ["sleep", "8000"]
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    awsElasticBlockStore:
      volumeID: vol-00dbdb0c6573658b7 
      fsType: ext4
  nodeSelector:
    DATABASE: "YES"
