---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: web-service 
  labels:
    app: studentapp
    component: WEB
spec:
  replicas: 10
  selector:
    matchLabels:
      app: studentapp
      component: WEB 
  template:
    metadata:
      labels:
        app: studentapp
        component: WEB
    spec:
      containers:
      - name: api 
        image: raghudevops33/deploy-web:v2
        ports:
        - containerPort: 80
        imagePullPolicy: Always
#      nodeSelector:
#        APPLICATION: "YES"
...
---
kind: Service
apiVersion: v1
metadata:
  name: web-svc
  labels:
    app: studentapp
    component: WEB
spec:
  type: LoadBalancer
  selector:
    app: studentapp
    component: WEB
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
...
