apiVersion: v1
kind: Service
metadata:
  name: demo-svc-np
  labels:
    app: studentapp
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31704
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: studentapp
