apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: studentapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - name: webservice
        image: raghudevops33/kube-demo
        ports:
        - containerPort: 80

