---
apiVersion: apps/v1 
kind: ReplicaSet 
metadata:
  name: mariadb 
  labels:
    app: studentapp
    component: DB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp
      component: DB
  template:
    metadata:
      labels:
        app: studentapp
        component: DB
    spec:
      containers:
      - name: mariadb 
        image: raghudevops33/stack-mariadb 
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mariadb-data
      nodeSelector:
        DATABASE: "YES"
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
...
---
kind: Service
apiVersion: v1
metadata:
  name: mariadb-svc
  labels:
    app: studentapp
    component: DB
spec:
  selector:
    app: studentapp
    component: DB
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
...
