apiVersion: v1
kind: Pod
metadata:
  name: demo2
spec:
  containers:
  - name: webservice 
    image: raghudevops33/kube-demo:latest
  - name: centos
    image: centos
    command: [ "sleep", "4000"]
